### ISSUE TITLE
Opening a file usually doesn't work, the file gets overwritten before display causing major issues

### ISSUE THREAD

**Issue by cclauss** [Cethric/HTMLEditor-Pythonista#12]

**Comment by Cethric** [comment]
Thanks for opening the issue.
Can you see something that I am missing, I am unable to get the thread to wait for the file to open before trying to save it.

**Comment by cclauss** [comment]
On line 307, you call wait_save() as if it was a function but it is a boolean.

**Comment by Cethric** [comment]
Fixed - Thanks
The event however does not register when
`wait_save = False`
changes to
`wait_save = True`
however it does when going the other way (True to False)

**Comment by Cethric** [comment]
This now only affects opening a file after one has already been opened
i.e.
- opening `test1.html` works
- opening `test2.html` after `test1.html` has been opened fails

**Comment by Cethric** [comment]
fixed, removed the use of unicode strings
