### ISSUE TITLE
import console will fail on non-Pythonista platforms

### ISSUE THREAD

**Issue by cclauss** [Cethric/HTMLEditor-Pythonista#14]
``` python
try:
    import ui
except ImportError:
    print "Using Dummy UI"
    import dummyUI as ui
import console
```

The try/except block is designed to work even on non-Pythonista platforms but on those platforms, the import console line would also throw an ImportError exception.  Should the import console be moved up inside the try block?

**Comment by Cethric** [comment]
Yes it should be however there is no placeholder class for it like their is for the ui, that will be done later along with making the dummyUI module a desktop ui module.

**Comment by Cethric** [comment]
see issue #16
